### ISSUE TITLE
App crashes on startup OS X 10.0.3

### ISSUE THREAD

**Issue by unforswearing** [import-io/import.io#6]
From the console: 

```
5/2/15 4:09:13.802 PM import.io[90852]: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.3 instead of 10.10.3. 
Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:

5/2/15 4:09:13.803 PM import.io[90852]: 0   CarbonCore                          0x00007fff861002b7 ___Gestalt_SystemVersion_block_invoke + 113
5/2/15 4:09:13.803 PM import.io[90852]: 1   libdispatch.dylib                   0x00007fff92f68c13 _dispatch_client_callout + 8
5/2/15 4:09:13.803 PM import.io[90852]: 2   libdispatch.dylib                   0x00007fff92f68b26 dispatch_once_f + 117
5/2/15 4:09:13.803 PM import.io[90852]: 3   CarbonCore                          0x00007fff86089456 _Gestalt_SystemVersion + 987
5/2/15 4:09:13.803 PM import.io[90852]: 4   CarbonCore                          0x00007fff860886e3 Gestalt + 144
5/2/15 4:09:13.803 PM import.io[90852]: 5   import.io                           0x0000000100001ae1 main + 50
5/2/15 4:09:13.803 PM import.io[90852]: 6   import.io                           0x0000000100001158 start + 52
```

**Comment by mjgp2** [comment]
Thanks for the report, it seems similar to [this issue](https://discussions.apple.com/thread/6987966).

If you delete and reinstall as suggested by Apple there does it fix the issue?

**Comment by unforswearing** [comment]
I have uninstalled/reinstalled twice, and just tried the method described in that post with no success. The app still crashes immediately on launch.

**Comment by Ganeshsankararaman** [comment]
We tried to recreate the issue, but we are unable to reproduce in the OS X versions 10.10.1 and 10.10.3

**Comment by mjgp2** [comment]
I understand this must be annoying, we'll keep looking into it.

**Comment by unforswearing** [comment]
This project looks very interesting to me and could potentially be a great help, so I was a bit disappointed when it wouldn't work for me. I really appreciate your looking into the issue.

**Comment by mjgp2** [comment]
We still can't reproduce and haven't had any other reports :(

**Comment by unforswearing** [comment]
I'm still having the issue on my personal laptop. I attempted to run the app on a different machine (running the same OS) -- the app opened, I was able to log in, but received a message stating "There was an error" and the app shut down. I didn't copy any console messages, and at this point I think I'm going to give up. Thanks for your help with this.

**Comment by mjgp2** [comment]
That's a shame, sorry.

What locale is your copy of OSX and what hardware are you running it on?

**Comment by unforswearing** [comment]
I'm in the US (`en_US.UTF-8`). My laptop is a late 2011 Macbook Pro and the other machine I tried this on is an early 2014 iMac.

**Comment by andrefaria** [comment]
Same thing happening in the new version of OS X - 10.11 Beta (15A215h).
